[package]
name = "prosa-ollama"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = "0.2"
prosa = "0.2"
prosa-utils = "0.2"
serde = "1"
tokio = "1"
thiserror = "2"
tracing = "0.1"
bytes = "1"
url = { version = "2", features = ["serde"] }
